<div class="container">
    <form method='POST' action="<?php echo $this->getUrl("crud/post/save")?>">
        <div class="form-group">
            <label for="name"><b>Name</b></label>
            <input type="text" class="form-control" id="name" placeholder="Enter a name" name="name">
        </div>
        <br>
        <button type="submit" class="btn btn-primary" name="createbtn">Submit</button>
    </form>
</div>
